### ISSUE TITLE
The Interactive Map is not Visible

### ISSUE THREAD

**Issue by MichaelEIC** [theblacksea/issues#12]
The interactive map for the HIV article here:

https://theblacksea.eu/index.php?idT=88&idC=88&idRec=1192&recType=multimedia

Is not visible. It should be the first image in the text.

The interactive map here:

https://theblacksea.eu/index.php?idT=88&idC=88&idRec=1139&recType=story

is not accessible

**Comment by victor-nitu** [comment]
That's likely an editing issue. Low priority for a tech point of view, anyone with editing privileges should be able to fix it. Will look into it.
