### ISSUE TITLE
Customised URLs

### ISSUE THREAD

**Issue by cpshaw99** [theblacksea/issues#13]
Require a feature and create and edit URLs for new and existing pages

**Comment by victor-nitu** [comment]
WONTFIX

**Comment by cpshaw99** [comment]
Is it that it can't be fixed? if so, then we keep it open to be added as a function of the new CMS

**Comment by mgax** [comment]
Wagtail gives us this feature for free by editing the "slug" field in the "promote" tab of an article edit page.
