### ISSUE TITLE
Mobile Phone Issue

### ISSUE THREAD

**Issue by MichaelEIC** [theblacksea/issues#14]
You created URLs for the mobile phone with 'm' in front of 'theblacksea.eu'

This means that, say, someone shares this article on Facebook, it can only be viewed as the mobile article, which looks stupid on a PC or Mac. 

You can check out the eggs story on The Black Sea Facebook site, for example.

The articles must be flexible, otherwise it's just ridiculous.

**Comment by germakoci** [comment]
@MichaelEIC the hits coming from mobile operating systems redirect automatically to url's with m.theblacksea.eu/... like https://mobile.nytimes.com/; I guess non-mobile OS should redirect outside the m.tbs url

**Comment by nathanschepers** [comment]
agreed wholeheartedly @nightsh what is involved in doing this?

**Comment by victor-nitu** [comment]
Some Apache rewrite / redirect rules. Will fix this as part of server maintenance actually.

**Comment by mgax** [comment]
m.theblacksea.eu will redirect to the main website (https://github.com/CRJI/theblacksea.eu/issues/23), so this problem is going away.
