### ISSUE TITLE
Preview not appearing on FB/ Twitter

### ISSUE THREAD

**Issue by MichaelEIC** [theblacksea/issues#16]
The preview did not appear on FB and Twitter for the story 'The Mafia Ambassador'

This has happened before.

Victor stated it is because the article was added as a 'http' and not as a 'https'.

We have to look into this to be sure it does not happen again

**Comment by victor-nitu** [comment]
It's a DIY process, not linked to our platform. If thumbnails are not correct, you have to tell the websites to rescrape them.
For Facebook: https://developers.facebook.com/tools/debug/sharing/
For Twitter: https://cards-dev.twitter.com/validator

**Comment by nathanschepers** [comment]
This process should go into the wiki of this repository. @MichaelEIC can you do this then we can close the issue? ask me if you need help.

**Comment by MichaelEIC** [comment]
Sure, I have tested this on a 'test' article for the Facebook, and even published a page called 'test' with image. Then I debugged it, but, as far as I can see, the problem is the same. There is no preview on Facebook.

**Comment by mgax** [comment]
We can close this issue. @nightsh can you please click the button? I don't have the rights.
