### ISSUE TITLE
social media

### ISSUE THREAD

**Issue by zsentek** [theblacksea/issues#3]
Social media sharing link needs to be fixed. 
With Facebook and Twitter, sharing doesn't work properly, it doesn't show the story, only shows the theblacksea.eu address. Please see the picture explaining
![screen shot 2017-07-27 at 14 09 49](https://user-images.githubusercontent.com/29794271/28669636-4f91b1be-72d5-11e7-99fe-e699a8c580fd.png)

**Comment by MichaelEIC** [comment]
This is continual problem which also happened with this article (August 26) which meant we could not share it on FB/Twitter with headline and image

https://theblacksea.eu/index.php?idT=88&idC=88&idRec=1328&recType=story
