### ISSUE TITLE
Authors page

### ISSUE THREAD

**Issue by zsentek** [theblacksea/issues#5]
The page where the authors are listed, some photos don't show. This is I think a ad blocker problem? This was fixed for the main page but not in the About section. See below

![screen shot 2017-07-27 at 14 12 14](https://user-images.githubusercontent.com/29794271/28669758-c21fa880-72d5-11e7-9f2d-977ce84c5a04.png)

**Comment by victor-nitu** [comment]
Ad blocker it is. Didn't realize that until now.
