### ISSUE TITLE
The Apostrophes that appear as Inverted Commas

### ISSUE THREAD

**Issue by MichaelEIC** [theblacksea/issues#7]
On the homepage and in stories apostrophes (') appear as inverted commas (") on some of the stories, but not all

For example: 'TURKISH PRESIDENT ERDOĞAN''S FAMILY IN SECRET OFFSHORE SHIP DEAL'

This does not occur when they appear in stories

**Comment by mgax** [comment]
Must be a quoting issue, maybe from the database or YAML file parsing? It will go away when we import the articles into wagtail.
